db: # 数据库
  driver: mysql # 数据库驱动
  configs:
    mysql:
      host: 127.0.0.1
      port: 3306
      user: root
      password: ${oc.env:APP_DB_PASSWORD}
      database: auth

log: # 日志
  to_console: true # 是否输出到控制台
  to_console_level: INFO # 日志级别(DEBUG, INFO, WARNING, ERROR, CRITICAL)
  to_file: true # 是否输出到文件
  to_file_level: INFO # 日志级别(DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_dir: app # 日志目录
  max_file_size: 10MB # 单个日志文件最大大小

auth_service:
  base_url: http://127.0.0.1:7777 # 认证服务url
  verify_access_token: /api/verify_access_token # 验证访问令牌
